version: '3'

services:
  database:
    image: mysql
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306

volumes:
  db_data:
